### ISSUE TITLE
Disagg dedup

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/datim-dedupe#1]
Right now, we are only deduping the "numerators", which are data elements with default COCs. 

The subquery which specifies the data element groups needs to be expaneded to include the disaggs as well.

**Comment by Markionium** [comment]
Maybe i am not understanding this correctly but from what i got from @larshelge we only dedup the aggregates?

**Comment by jason-p-pickering** [comment]
Well, if you look at Mike's email from the other day, he says there is a need to dedupe the disaggs as well, so it is something we need to clarify.

**Comment by jason-p-pickering** [comment]
We will need to dedupe the disaggs, as well as very likely the targets, but this is pending the final spec. Closing this for now, as the dedupe query will return the destination data element/coc/period/OU where the deduplication factor needs to be applied.
