### ISSUE TITLE
Need disaggregation in the UI

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/datim-dedupe#18]
![missing_disagg](https://cloud.githubusercontent.com/assets/2968061/6330589/ecb23470-bb79-11e4-8c43-d10cb5762db4.png)

Disaggregation needs to be in the UI as well.

**Comment by jason-p-pickering** [comment]
Hi mark,
Bumping this, as I think it is quite urgent. 
Do you think you can add the disagg to the UI?

Regards,
Jason

**Comment by Markionium** [comment]
Added the disagg. Currently it shows the (default) value also, not sure if we should keep that or translate that into something different.
