### ISSUE TITLE
How to handle situations when there are both concordant and discordant duplicates?

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/datim-dedupe#2]
We are getting some "duplicate" rows in the current SQL function in situations when we have three or more values for a given sourceid/dataelementid/periodid/COC. If two values are concordant and one of them is discordant, we get some duplicates (look at TX_CURR (N, DSD, Age/Sex Aggregated): Receiving ART Robin Site. (9999 Demoland USAID IM) shows up twice, with two different duplicate_type. 

What needs to happen here is that if ANY of the values are discordant, then it is discordant. 

We will need to clarify this, and if there is no need to separate between concordant and discordant types of duplicates, this issue may go away by itself.

**Comment by Markionium** [comment]
Is this one still relevant?

**Comment by jason-p-pickering** [comment]
@invalid I think
