### ISSUE TITLE
Filter for results and targets

### ISSUE THREAD

**Issue by larshelge** [dhis2/datim-dedupe#20]
Add support for filtering results and targets data. Add a drop-down with options for "Results" and "Targets" which should filter the de-dupe list accordingly.

**Comment by Markionium** [comment]
Would this be client side or server side?

**Comment by Markionium** [comment]
On second thought, i assume this should be server side. If we implement server side paging, client side filtering would only be for the current page, which does not really seem to make sense.

**Comment by Markionium** [comment]
Added a filter dropdown that sends a value to the server in c7f8e33bd57fd47c9a3b355c5d44b5ede35532f2

Currently whenever selecting either targets or results the app will send `var=tr:targets` or `var=tr:results`. When neither is selected it won't send the tr parameter. (This might not be valid as the vars might be required... in that case i suggest it sends `var=tr:both` or `var=tr:all`

**Comment by Markionium** [comment]
Done since 77338c3e23541da273ddc51c0ca3d67105a71070. See https://github.com/dhis2/datim-dedupe/blob/d74308c5b28d14dae4222c032b06f27395b9dc8c/README.md for updated install instructions.
