### ISSUE TITLE
Change client side filtering of resolved values to server side?

### ISSUE THREAD

**Issue by Markionium** [dhis2/datim-dedupe#22]
Currently the include resolved values filters on the client, however i guess when implementing the paging, it would make most sense to do this server side also.

We should determine what SQLView "var" we will use for this.

Since we seem to have picked 2 letter acronyms perhaps we can go with `re` or `rs`.

**Comment by jason-p-pickering** [comment]
yeah, sure. can make this change. Will suggest "sr" for show resolved.

**Comment by jason-p-pickering** [comment]
Fixed in e2ed9e8bdafe93d40637403b359389615c89136c in paging branch.
