### ISSUE TITLE
Showing resolved dups?

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/datim-dedupe#23]
From MG  "One more issue I noted is that when you do dedup and then you return to the same OU/period, you are prompted to do dedup again on the ones that have already been resolved.  We should probably not bring those back as the idea is to get to nothing let to resolve on the list.  We can worry about the need to edit/revised later. "

**Comment by Markionium** [comment]
Right, so basically currently this would be disabling the current functionality until further notice?
