### ISSUE TITLE
Paging is funky

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/datim-dedupe#27]
Login  to test.datim.org and select Zambia/Oct 2014-2015. 

Select page 1. You see 50/85. 
![selection_003](https://cloud.githubusercontent.com/assets/2968061/6673321/6c0b0a50-cc12-11e4-881a-8b6d33624d00.png)

Select page 2. 

![selection_004](https://cloud.githubusercontent.com/assets/2968061/6673333/78ae9f88-cc12-11e4-9247-dc90a107f00b.png)

You see 35/85. Is this intuitive?

Somehow, I would expect to see 1-50/85 for page 1 and 51-85/85 for page 2? 

Somehow, I would expect to see 1-50

**Comment by Markionium** [comment]
Yeah you're right that doesn't really make sense. Will fix it tomorrow.

I guess `Showing 1-50 of 85` and `Showing 51-85 of 85` would make the most sense.
