### ISSUE TITLE
Some dupes are showing no orgunit. This should not be the case. 

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/datim-dedupe#30]
![image](https://cloud.githubusercontent.com/assets/2968061/7000856/8465b5f2-dc2d-11e4-9687-ec170e03f952.png)

**Comment by jason-p-pickering** [comment]
@Markionium , this is being caused by targets set at the national level. See part of the response below. (XXXX is not in the response, but for obfuscation)

["","","","","Ethiopia","3","TX_CURR (N, DSD) TARGET: Receiving ART","(default)","XXXXX","XXXXXX","XXXXXX","6140","UNRESOLVED","IH1kchw86uA","f9BaCsI9PGn","HllvX50cXC0","02c3865cede939d29408e5228799c9df","16","1538","TARGETS"]

**Comment by Markionium** [comment]
Right.. ok so if the string of all the combined level3-5 is empty we use the normal OU field.

**Comment by jason-p-pickering** [comment]
Yes  that would seem like an easy fix.

**Comment by Markionium** [comment]
Resolved in 0.0.13
