### ISSUE TITLE
Improve language in UI

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/datim-dedupe#39]
Currently "Show all" is a bit confusing, at this really refers to showing both RESOVLED as well as UNRESOLVED duplicates. It does not really show all of them. We should think of some better language here.

**Comment by jason-p-pickering** [comment]
ALso "Mark all duplicates as" does not really refer to all duplicates, just the duplicates on the current page.

**Comment by Markionium** [comment]
I agree on both points.

Perhaps we can rename "Show all"  to "Include resolved" as that is more representative of what is happening?

For the "Mark all duplicates as" i don't really know what we could do.. my first thought would be "Mark duplicates as" or perhaps "for these duplicates." behind the buttons as that will create a more logical sentence.
