### ISSUE TITLE
Add ability to customize page size  and input page number

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/datim-dedupe#47]
6.	Option to display more results on one page (should be customizable) 
7.	Ability to type in page number at bottom rather than scrolling through 10 pages at a time. Loading a new set of pages can take up to a minute. If you need to get to page 200, this can take up to 20 minutes of clicking Next.

**Comment by Markionium** [comment]
Regarding number two.. what is a realistic use case where someone would need to get to page 20? 

I get the request for the functionality but i don't know what is the idea behind the use case this would realistically solve and in which use case this would be beneficial over a search function.

As i can currently judge it there is no way of knowing what is on page 200.

**Comment by jason-p-pickering** [comment]
Yeah, I tend to agree, and think that some more intelligent grouping/searching functionality is probably more useful than this. 

Having said that, the use case which I did discuss with one user was being able to divide up the work along multiple people. So, the first person would start with page 1 and the second with page 100. Also, it is probably trivial to implement, since it should already be supported in the query?

**Comment by Markionium** [comment]
Right, that is correct, however this "dividing up" might cause trouble when working with pages as there might be a scenario when a dedupe ends up on a different page.

It is trivial to implement, i'm just trying to make sure we're implementing it for a reason that won't cause more trouble :)
