### ISSUE TITLE
Period type in sqlview

### ISSUE THREAD

**Issue by Markionium** [dhis2/datim-dedupe#5]
Currently the sql view as my fake data one shows currently does not contain a period type. 

If the goal is that i pass a period type to the view then this is not really important to return.

Otherwise it might be useful to return that.

**Comment by jason-p-pickering** [comment]
Yes, ok, that should be possible, however, I think what you need is the actual period in question, i.e. "201401", not actually the type right?

**Comment by Markionium** [comment]
Yes that sounds correct. If you can add that that would be great. (I could then figure out the type myself if that is eventually needed)

**Comment by jason-p-pickering** [comment]
Fixed in 51de656722569bde9108c8906187b2e78590f009

How do I do this in the commit message? ??
