### ISSUE TITLE
Uid for things that are used to save against the dedupe mechanism

### ISSUE THREAD

**Issue by Markionium** [dhis2/datim-dedupe#6]
From what i know i will have to save the "adjusted" value. Therefore i am sure i will need a few uid (preferably).

Currently the orgunit name is returned, could you also return the uid? I am not sure what else is needed, but i would guess dataElement as well.

**Comment by jason-p-pickering** [comment]
Yes, that is certainly possible.

**Comment by Markionium** [comment]
Great thanks!
