### ISSUE TITLE
Deploy fix to properly display resolved deduplications

### ISSUE THREAD

**Issue by jknuep** [dhis2/datim-dedupe#61]
A few issues have been noticed when using the dedup app, which incorrectly displays the "resolved" duplications as not having been resolved.  This has been observed in both DATIM and DATIM4U.

A fix had been written but has yet to be deployed: https://raw.githubusercontent.com/dhis2/datim-dedupe/master/sql/app/dedupe_plpgsql.sql

The relevant ticket for DATIM4U: https://github.com/pepfar-datim/DATIM4U/issues/239
The fix was used to test the above ticket (on 2017.02.14) by @jason-p-pickering.  The OU's results were imported into sandbox dev-analytics.datim.org and confirmed issue was resolved.

**Comment by jason-p-pickering** [comment]
@jknuep I beleive this has been resolved. Related tickets are closed.
