### ISSUE TITLE
Possibility for identifier for dedupe combinations?

### ISSUE THREAD

**Issue by Markionium** [dhis2/datim-dedupe#8]
Would it be possible to add a column that has the same value  for the rows that belong together?

As i am currently trying to group the rows together that belong to the same dedupe, i find myself having to concatenate all the strings to sort of generate a "key" to identify which rows belong together.

If this is not possible could you tell me which ones i can use to identify the rows? For example are `startdate` and `enddate` also relevant?

```js
            recordObject[0], //oulevel2_name
            recordObject[1], //oulevel3_name
            recordObject[2], //oulevel4_name
            recordObject[3], //oulevel5_name
            recordObject[4], //orgunit_name
            recordObject[5], //orgunit_level
            recordObject[6], //startdate
            recordObject[7], //enddate
            recordObject[8], //dataelement
            recordObject[9]  //disaggregation
```

**Comment by jason-p-pickering** [comment]
OK. Something like some sort of fake key? I would think the OU/period/dataelement/catcombo UIDs should provide this, but we can certainly add some sort of hash if this makes things easier for you to work with?

**Comment by Markionium** [comment]
Ok if you could add those uids then that is good enough, i would need those to save the value back again anyhow, or well at least a couple of them.

If you could let me know which ones are relevant that would be great. If OU/period/dataelement/catcombo are the ones that is great then i can use those instead of the list of 9 above :)

**Comment by jason-p-pickering** [comment]
Would it be OK just to return the UIDs of the required objects, and then you fetch everything you need (i.e names) from the API instead? This might be more efficient?

**Comment by Markionium** [comment]
Does it make a big difference for the query execution time? For dataElement and orgunit i might just need the name. Depending on how many different ones there are that would be that amount of calls, or a heavy filter api call. If it is sort of trivial for you then it would be nice to return the name and id. It would make the client side processing a bit lighter.

As far as i can tell the only things i will need to save the deduped values are the dedupe mechanism id, the dataelement id, period and orgunit id. 

The orgunit name would only be to show to which org unit it applies. (See ui mockup from Lars below) 

PS: The data element and mechanism are not displayed there, but i guess they should be? @larshelge 

![dedupe](https://cloud.githubusercontent.com/assets/2134901/5975795/d2e7dc0e-a885-11e4-8e65-c399b141cecd.png)

**Comment by jason-p-pickering** [comment]
0175d47492414c80c0a70b5193048f960b606a39 partially addresses this, but we will need to figure out the exact duplication logic once the spec has been provided.

**Comment by jason-p-pickering** [comment]
Closing this as I think it has been implemented, but otherwise is a bit of a jumble of different issues.
